org: ivanwu7887
app: typescript-http-api
service: typescript-http-api
frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs14.x
  stage: dev
  region: ap-southeast-2
  httpApi:
    cors: true
  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - dynamodb:Query
            - dynamodb:Scan
            - dynamodb:GetItem
            - dynamodb:PutItem
            - dynamodb:UpdateItem
            - dynamodb:DeleteItem
          Resource: "arn:aws:dynamodb:${aws:region}:*:table/*"
        - Effect: Allow
          Action:
            - sns:*
          Resource: "arn:aws:sns:${aws:region}:*:*"
        - Effect: Allow
          Action:
            - sqs:*
          Resource: "arn:aws:sqs:${aws:region}:*:*"

functions:
  getUser:
    handler: users/get.get
    events:
      - httpApi:
          path: /users
          method: get
  registerUser:
    handler: users/register.register
    events:
      - httpApi:
          path: /users
          method: post
    environment:
      USER_SNS_ARN: !Ref UserTopic
  createUser:
    handler: users/create.create
    events:
      - sns:
          arn: !Ref UserTopic
          topicName: UserTopic
  listMessageBoard:
    handler: messageBoards/list.list
    events:
      - httpApi:
          path: /messageBoards
          method: get
  registerMessageBoard:
    handler: messageBoards/register.register
    events:
      - httpApi:
          path: /messageBoards
          method: post
    environment:
      MESSAGE_BOARD_SQS_URL: !Ref MessageBoardQueue
  createMessageBoard:
    handler: messageBoards/create.create
    events:
      - sqs:
          arn: !GetAtt MessageBoardQueue.Arn
  registerMessage:
    handler: messages/register.register
    events:
      - httpApi:
          path: /messages
          method: post
    environment:
      MESSAGE_SNS_ARN: !Ref MessageTopic
  createMessage:
    handler: messages/create.create
    events:
      - sns:
          arn: !Ref MessageTopic
          topicName: MessageTopic

plugins:
  - serverless-plugin-typescript

resources:
  Resources:
    usersTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: users
        AttributeDefinitions:
          - 
            AttributeName: id
            AttributeType: S
          - 
            AttributeName: email
            AttributeType: S
        KeySchema:
          - 
            AttributeName: id
            KeyType: HASH
          - 
            AttributeName: email
            KeyType: RANGE
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
    messagesTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: messages
        AttributeDefinitions:
          - 
            AttributeName: id
            AttributeType: S
          - 
            AttributeName: messageBoardId
            AttributeType: S
        KeySchema:
          - 
            AttributeName: id
            KeyType: HASH
          - 
            AttributeName: messageBoardId
            KeyType: RANGE
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
    messageBoardsTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: messageBoards
        AttributeDefinitions:
          - 
            AttributeName: id
            AttributeType: S
        KeySchema:
          - 
            AttributeName: id
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
    UserTopic:
      Type: AWS::SNS::Topic
      Properties:
        TopicName: UserTopic
        DisplayName: UserTopic
    MessageBoardQueue:
      Type: AWS::SQS::Queue
      Properties:
        QueueName: MessageBoardQueue
        VisibilityTimeout: 300
    MessageTopic:
      Type: AWS::SNS::Topic
      Properties:
        TopicName: MessageTopic
        DisplayName: MessageTopic